AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  AudioTranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: audio-transcription
      # Handler: audio_transcription.lambda_handler
      # Runtime: python3.10
      # CodeUri: ./serverless
      PackageType: Image
      MemorySize: 128
      Timeout: 10
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: v1

Outputs:
  MyLambdaFunctionOutput:
    Value: !Ref AudioTranscriptionFunction
