AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  AudioTranscriptionDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: audio-transcription-dependencies-layer
      ContentUri: ./serverless/dependencies
    Metadata:
      BuildMethod: python3.10
      BuildCommand: pip install --target ./serverless/dependencies -r requirements.txt
  AudioTranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: audio-transcription
      Handler: audio_transcription.lambda_handler
      Runtime: python3.10
      CodeUri: ./serverless
      MemorySize: 128
      Timeout: 10
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref FilmAndAudioBucket
            Events:
              - s3:ObjectCreated:*
      Layers:
        - !Ref AudioTranscriptionDependenciesLayer

  FilmAndAudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: language-bucket-liam-idrovo

Outputs:
  MyLambdaFunctionOutput:
    Value: !Ref AudioTranscriptionFunction

  MyS3BucketOutput:
    Value: !Ref FilmAndAudioBucket
