AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  FilmProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: film_processing
      Handler: film_processing.lambda_handler
      Runtime: python3.10
      CodeUri: ./serverless
      MemorySize: 128
      Timeout: 10

  FilmAndAudioPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref FilmProcessingFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub arn:aws:s3:::language-bucket-liam-idrovo

Outputs:
  MyLambdaFunctionOutput:
    Value: !Ref FilmProcessingFunction
  FilmProcessingFunctionArn:
    Description: FilmProcessingFunction Arn
    Value: !GetAtt FilmProcessingFunction.Arn
