name: Deploy Lambda hosting Whisper Model

on:
  push:
    branches:
      - main
    paths:
      - "serverless/whisper/**"
jobs:
  deploy-whisper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0

      - name: Install AWS CLI and AWS SAM CLI
        run: |
          pip install awscli aws-sam-cli
      - name: Deploy Whisper Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd serverless/whisper
          sam build --use-container -t template.yaml
          sam deploy --resolve-image-repos --no-confirm-changeset --no-fail-on-empty-changeset --region us-east-1 --stack-name language-recognition --resolve-s3 --capabilities CAPABILITY_IAM
