name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0

      - name: Install AWS CLI and AWS SAM CLI
        run: |
          pip install awscli aws-sam-cli

      - name: Deploy AWS Resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

          sam build --use-container -t template.yaml
          sam deploy --resolve-image-repos --no-confirm-changeset --no-fail-on-empty-changeset --region us-east-1 --stack-name language-recognition --resolve-s3 --capabilities CAPABILITY_IAM
